-- CreateDriver

use PUBLIC_TRANSPORTATION;
go
CREATE VIEW PICKUP_LOCATION
AS
SELECT PASS_NUM, LAST_NAME, ZIP, STATE
FROM RIDERS;

select * from PICKUP_LOCATION;

--To drop view
DROP VIEW PICKUP_LOCATION;